package dosPaquetes;

import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author DESKTOP-6A9B
 */
public class RegistroDeportivo extends javax.swing.JDialog {

    private boolean isTableVisible;
    private DefaultTableModel modeloTabla;
    private AccesoDeportivo accesoDeportivo;

    public RegistroDeportivo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        this.modeloTabla = (DefaultTableModel) jTable1.getModel();
        this.accesoDeportivo = (AccesoDeportivo) parent;
    }

    public DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }

    public void actualizarTabla() {
        SwingUtilities.invokeLater(() -> {
            modeloTabla.fireTableDataChanged();
            jTable1.repaint();
        });
    }

    public void desplazarVistaTabla() {
        int lastRow = modeloTabla.getRowCount() - 1; // Índice de la última fila
        if (lastRow >= 0) {
            jTable1.scrollRectToVisible(jTable1.getCellRect(lastRow, 0, true));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelREGISTRODEPORTIVO = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1VerOcultartabla = new javax.swing.JButton();
        jButtonAnadirHijo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelDeporte = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelNivel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabelTurno = new javax.swing.JLabel();
        jLabelRenovación = new javax.swing.JLabel();
        jCheckBoxTrimestral = new javax.swing.JCheckBox();
        jCheckBoxAnual = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabelSelecciónDeporte = new javax.swing.JLabel();
        jButtonMATRICULAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelREGISTRODEPORTIVO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelREGISTRODEPORTIVO.setText("REGISTRO DEPORTIVO");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(617, 468));
        jPanel1.setMinimumSize(new java.awt.Dimension(617, 468));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMaximumSize(new java.awt.Dimension(576, 184));
        jPanel2.setMinimumSize(new java.awt.Dimension(576, 184));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1VerOcultartabla.setText("Ver/Ocultar tabla");
        jButton1VerOcultartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1VerOcultartablaActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1VerOcultartabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 26, -1, -1));

        jButtonAnadirHijo.setText("Añadir Hijo");
        jButtonAnadirHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirHijoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAnadirHijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 26, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Fecha Nacimiento", "Deporte", "Nivel"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 75, 545, 93));

        jLabelDeporte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDeporte.setText("Deporte");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tenis", "Padel", "Squash" }));

        jLabelNivel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNivel.setText("Nivel");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inicial", "Medio", "Pro", "Master" }));

        jLabelTurno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTurno.setText("Turno");

        jLabelRenovación.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRenovación.setText("Renovación");

        jCheckBoxTrimestral.setText("Trimestral");

        jCheckBoxAnual.setText("Anual");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Mañana");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Tarde");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDeporte)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelTurno)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNivel)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelRenovación)
                            .addComponent(jCheckBoxTrimestral)
                            .addComponent(jCheckBoxAnual)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDeporte)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNivel)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTurno)
                    .addComponent(jLabelRenovación))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTrimestral)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jCheckBoxAnual))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelSelecciónDeporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSelecciónDeporte.setText("Selección Deporte");

        jButtonMATRICULAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMATRICULAR.setText("MATRICULAR");
        jButtonMATRICULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMATRICULARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelSelecciónDeporte)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMATRICULAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabelREGISTRODEPORTIVO)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelREGISTRODEPORTIVO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSelecciónDeporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonMATRICULAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1VerOcultartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1VerOcultartablaActionPerformed
        // Cambia la visibilidad de la tabla
        if (isTableVisible) {
            jScrollPane1.setVisible(false);
            jButton1VerOcultartabla.setText("Ver tabla");
        } else {
            jScrollPane1.setVisible(true);
            jButton1VerOcultartabla.setText("Ocultar tabla");
        }
        isTableVisible = !isTableVisible;
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton1VerOcultartablaActionPerformed

    private void jButtonAnadirHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirHijoActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        AñadirHijo dialog = new AñadirHijo(accesoDeportivo, true, tableModel);

        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonAnadirHijoActionPerformed

    private void jButtonMATRICULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMATRICULARActionPerformed
        JOptionPane.showMessageDialog(null, "¡Matrícula guardada!", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonMATRICULARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeportivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeportivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeportivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeportivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroDeportivo dialog = new RegistroDeportivo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1VerOcultartabla;
    private javax.swing.JButton jButtonAnadirHijo;
    private javax.swing.JButton jButtonMATRICULAR;
    private javax.swing.JCheckBox jCheckBoxAnual;
    private javax.swing.JCheckBox jCheckBoxTrimestral;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabelDeporte;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelREGISTRODEPORTIVO;
    private javax.swing.JLabel jLabelRenovación;
    private javax.swing.JLabel jLabelSelecciónDeporte;
    private javax.swing.JLabel jLabelTurno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
